[general]
live_config_reload = true
import = [
  "/home/toroidalfox/.config/alacritty/themes/breeze-dark.toml",
  "/home/toroidalfox/.config/alacritty/themes/breeze-light.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Cascadia Mono"
style = "Bold"

[font.bold_italic]
family = "Cascadia Mono"
style = "Bold Italic"

[font.italic]
family = "Cascadia Mono"
style = "Italic"

[font.normal]
family = "Cascadia Mono"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.90
blur = true
resize_increments = true

[window.dimensions]
columns = 110
lines = 36
