[[language]]
name = "rust"

[language.auto-pairs]
'(' = ")"
'{' = '}'
'[' = ']'

[[language]]
name = "python"
language-servers = [
  { name = "pyright" },
  { name = "ruff" },
  # { name = "pyright", except-features = ["format"] },
  # { name = "ruff", only-features = ["format"] },
]
[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
roots = [".taplo.toml"]

[[language]]
name = "c"
formatter = { command = "clang-format", args = ["-style=llvm", "-"] }
auto-format = true

[[language]]
name = "cpp"
formatter = { command = "clang-format", args = ["-style=llvm", "-"] }
auto-format = true
