#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "ToroidalFox"
email = "toroidalfox@gmail.com"

[revsets]
log = 'ancestors(@, 8) | ancestors(visible_heads(), 8) | ancestors(bookmarks(), 8) | ancestors(remote_bookmarks(), 8) | divergent()'
