[colors.bright]
black = "#1c1a24"
blue = "#005ce8"
cyan = "#00aac8"
green = "#50c850"
magenta = "#ba0eb8"
red = "#f83636"
white = "#ffffff"
yellow = "#de6602"

[colors.dim]
black = "#44424c"
blue = "#1484c0"
cyan = "#1eaaa0"
green = "#648c64"
magenta = "#885488"
red = "#c6605e"
white = "#e6e6e6"
yellow = "#ae9802"

[colors.normal]
black = "#383a42"
blue = "#0070d4"
cyan = "#0a96b4"
green = "#50a050"
magenta = "#a626a4"
red = "#e4564a"
white = "#fafafa"
yellow = "#c28402"

[colors.primary]
background = "#fafafa"
bright_foreground = "#050224"
dim_foreground = "#44424c"
foreground = "#383a42"
