[colors.bright]
black = "#7f8c8d"
red = "#c0392b"
yellow = "#fdbc4b"
green = "#1cdc9a"
blue = "#3daee9"
magenta = "#8e44ad"
cyan = "#16a085"
white = "#ffffff"

[colors.dim]
black = "#31363b"
red = "#783228"
yellow = "#b65619"
green = "#17a262"
blue = "#1b668f"
magenta = "#614a73"
cyan = "#186c60"
white = "#63686d"

[colors.normal]
black = "#232627"
red = "#ed1515"
yellow = "#f67400"
green = "#11d116"
blue = "#1d99f3"
magenta = "#9b59b6"
cyan = "#1abc9c"
white = "#fcfcfc"

[colors.primary]
background = "#161718"
bright_foreground = "#ffffff"
dim_foreground = "#eff0f1"
foreground = "#fcfcfc"
