theme = "onedark-transparent"

[editor]
line-number = "relative"
idle-timeout = 0
color-modes = true

[editor.statusline]
left = ["spinner", "file-name"]
center = ["mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
